# This file goes in your ~/.config/lineapplefolder
	Joystick 0 = 4
	Computer Emulation = 2
	Video Emulation =	6
	Emulation Speed =	10
	Fullscreen =	0
        Screen Width  = 1020 #560
        Screen Height = 768 #384

